#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

//#define __SAMD21E18A__

#define VENDOR_NAME "Adafruit Industries"
#define PRODUCT_NAME "DSP Pedal"
#define VOLUME_LABEL "PEDALBOOT"
#define INDEX_URL "http://adafru.it/3505"
#define BOARD_ID "SAMD21G18A-Metro-v0"

#define USB_VID 0x239A
#define USB_PID 0x0013

#define LED_PIN PIN_PA22
#define LED_TX_PIN PIN_PA28
#define LED_RX_PIN PIN_PB23

#define BOARD_NEOPIXEL_PIN PIN_PA27
#define BOARD_NEOPIXEL_COUNT 1

#define FLASH_NUM_ROWS 512

#define SPI_SERCOM SERCOM1
#define SPI_FLASH_SS PIN_PA17
#define SPI_FLASH_MOSI PINMUX_PA18C_SERCOM1_PAD2
#define SPI_FLASH_MISO PINMUX_PA16C_SERCOM1_PAD0
#define SPI_FLASH_SCLK PINMUX_PA19C_SERCOM1_PAD3

#define DSP_RESET_PIN PIN_PA03

#define SPI_FLASH_ADDRSIZE 24

#endif
